### PR TITLE
Use action/checkout v4 instead of v2 in tests

### PR DESCRIPTION
**Pull request by mlocati**

### CODE REVIEW

**Comment by jon-turney** [comment]
Oh my! That's wrong! Well spotted!

But I think that should be `uses: ./` everywhere, so we use the action from the currently checked out repository.

**Comment by mlocati** [comment]
> But I think that should be `uses: ./` everywhere

That's what we currently have: see for example:

```yml
    - uses: actions/checkout@v2

    - name: Install Cygwin
      uses: ./
      with:
        platform: ${{ matrix.platform }}
        packages: ${{ matrix.packages }}
        add-to-path: false
```

> so we use the action from the currently checked out repository

We need to checkout the repo: the action doesn't do that automatically.

**Comment by mlocati** [comment]
PS: about the failing tests see the "Installer freezes in windows-2022 GitHub Action" thread of https://cygwin.com/pipermail/cygwin/2024-October/thread.html

**Comment by jon-turney** [comment]
Sorry, completely misunderstood this. Somehow my brain decided the v4 tag was the version of this action, not the checkout action. More coffee needed obviously.

So this is just "update the version of the checkout action in tests", and obviously right.

Thanks

**Pull request merged**
